### ISSUE TITLE
The submit_payment_loop fails

### ISSUE THREAD

**Issue by mpnowacki-reef** [Chia-Network/pool-reference#156]
`wallet_rpc_client.send_transaction_multi` fails, log contains:

```
2021-07-12T01:57:27.189 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/private/var/root/p/pool-reference/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/private/var/root/p/pool-reference/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 740, in send_transaction_multi
    await wallet.push_transaction(transaction)
AttributeError: 'PoolWallet' object has no attribute 'push_transaction'
```

**Comment by wearechiarex** [comment]
You have to check your wallet is working on Chia-Blockchain. Could you check it?

**Comment by mariano54** [comment]
You're using the wrong wallet_id. You should use wallet_id 1: standard wallet.
