### ISSUE TITLE
 Fatal error on SSL transport

### ISSUE THREAD

**Issue by Soullnik** [Chia-Network/pool-reference#163]
![image](https://user-images.githubusercontent.com/52292226/125418365-95610c31-023f-4210-9000-bce5b27d9998.png)

**Comment by yhhwpp** [comment]
I also encountered this problem

after running pool for a while ， throw the following error:

``` python
WARNING:root:Not synced, waiting
WARNING:root:Waiting for wallet sync
INFO:root:Cancelled create_payments_loop, closing
INFO:root:Cancelled get_peak_loop, closing
INFO:root:Cancelled collect_pool_rewards_loop, closing
INFO:root:Cancelled confirm partials loop, closing
INFO:root:Cancelled submit_payment_loop, closing
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f8246465510>
transport: <_SelectorSocketTransport closing fd=10>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 870, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 680, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 874, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 683, in _fatal_error
    self._force_close(exc)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 695, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 691, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

```
