### ISSUE TITLE
View Pool Login Link "unsupported operand type(s) for /: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by Bingo821227** [Chia-Network/pool-reference#172]
unsupported operand type(s) for /: 'int' and 'NoneType'

Pool Login Link

Something went wrong

It is a one-time login link that can be used to log in to a pool's website. It contains a signature using the farmer's key from the plot NFT. Not all pools support this feature. Learn More

![截屏2564-07-14 19 09 44](https://user-images.githubusercontent.com/41192879/125619850-9cface51-f053-4290-9e76-28241a2fefeb.png)
![截屏2564-07-14 19 11 55](https://user-images.githubusercontent.com/41192879/125619920-8e88be4f-c427-4390-bb17-0bf54d117351.png)

**Comment by Tomouck** [comment]
hi,
I'm encountering the same issue.
Apple mac mini M1
macOS Big Sur 11.4

Chia blockchain 1.2.1
Electron 11.4.10
node 12.18.3
V8 8.7.220.31

**Comment by qq597353** [comment]
> 嗨，
> 我遇到了同样的问题。
> 苹果 mac mini M1
> macOS Big Sur 11.4
> 
> Chia
> 区块链 1.2.1 Electron 11.4.10
> 节点
> 12.18.3 V8 8.7.220.31

update 1.2.2

**Comment by Tomouck** [comment]
update 1.2.2 solved the issue

**Comment by mogaal** [comment]
Hello, I am facing the same issue and I am in `1.2.2.dev37` (pulled latest) and I am facing exactly the same error.

```
2021-07-19T10:20:15.479 farmer chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/mogaal/workspace/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/mogaal/workspace/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/mogaal/workspace/chia-blockchain/chia/rpc/farmer_rpc_api.py", line 120, in get_pool_login_link
    login_link: Optional[str] = await self.service.generate_login_link(launcher_id)
  File "/home/mogaal/workspace/chia-blockchain/chia/farmer/farmer.py", line 549, in generate_login_link
    authentication_token = get_current_authentication_token(authentication_token_timeout)
  File "/home/mogaal/workspace/chia-blockchain/chia/protocols/pool_protocol.py", line 170, in get_current_authentication_token
    return uint64(int(int(time.time() / 60) / timeout))
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

```

**Comment by mogaal** [comment]
@mariano54 should we reopen this issue?
