### ISSUE TITLE
[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1131)')]

### ISSUE THREAD

**Issue by mapleaj** [Chia-Network/pool-reference#173]
I followed the readme.md to install , but it can not work. Errors like below,how should I do?
I already installed openssl.system was ubuntu 20.4

`(venv) pool@plot-machine:~/pool-reference$ sudo ./venv/bin/python -m pool
Traceback (most recent call last):
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pool/pool-reference/pool/__main__.py", line 2, in <module>
    main()
  File "/home/pool/pool-reference/pool/pool_server.py", line 291, in main
    asyncio.run(start_pool_server())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/pool/pool-reference/pool/pool_server.py", line 260, in start_pool_server
    await server.start()
  File "/home/pool/pool-reference/pool/pool_server.py", line 58, in start
    await self.pool.start()
  File "/home/pool/pool-reference/pool/pool.py", line 188, in start
    self.blockchain_state = await self.node_rpc_client.get_blockchain_state()
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/chia/rpc/full_node_rpc_client.py", line 27, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/chia/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/pool/pool-reference/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host localhost:8555 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1131)')]
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: `

**Comment by mariano54** [comment]
Are you running the full node on the same network as the pool?
If you run testnet9 pool, you should run tesntet9 node

**Comment by mapleaj** [comment]
> Are you running the full node on the same network as the pool?

yes.same machine.

> If you run testnet9 pool, you should run tesntet9 node

I want to run it at mainnet

**Comment by growersun** [comment]
same error
