### ISSUE TITLE
ERROR    Unexpected error in collect_pool_rewards_loop

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#181]
Problem started after first XCH drop in pool.
```
2021-07-16T12:28:16.650 pool root                         : ERROR    Unexpected error in collect_pool_rewards_loop: {'error': 'coin_solutions', 'success': False} Traceback (most recent call last):
  File "/home/chiarex/pool-reference/pool/pool.py", line 333, in collect_pool_rewards_loop
    push_tx_response: Dict = await self.node_rpc_client.push_tx(spend_bundle)
  File "/home/chiarex/pool-reference/venv/lib/python3.8/site-packages/chia/rpc/full_node_rpc_client.py", line 144, in push_tx
    return await self.fetch("push_tx", {"spend_bundle": spend_bundle.to_json_dict()})
  File "/home/chiarex/pool-reference/venv/lib/python3.8/site-packages/chia/rpc/rpc_client.py", line 45, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'coin_solutions', 'success': False}
```

**Comment by mariano54** [comment]
There is a recent breaking change in chia-blockchain that renames coin_solutions to coin_spends.

We will try to revert this breaking change before next release.

**Comment by mariano54** [comment]
This has been fixed in main:
https://github.com/Chia-Network/chia-blockchain/commit/8f214e4f5f0d1f33c3d3bac57d72a6814f40ee26
