### ISSUE TITLE
400 message="Bad status line 'invalid HTTP method'"

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#182]
I saw in pool-reference logs.
```
2021-07-16T10:45:32.524 pool aiohttp.server               : ERROR    Error handling request
Traceback (most recent call last):
  File "/home/chiarex/pool-reference/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

**Comment by chrishp** [comment]
Did you find a solution?

**Comment by ppolewicz** [comment]
it's not really a problem. Someone is just hitting your pool with an invalid http method.
