### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: 400

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#186]
Testing with:

pool_url: https://127.0.0.1:80

And getting BadSatusLine error when connecting to pool through Chia app:

Traceback (most recent call last):
  File "/home/chrisvm/chia_pool/pool-reference/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/chrisvm/chia_pool/pool-reference/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by ppolewicz** [comment]
you are using port 80 which is traditionally HTTP, with a HTTPS address. I doubt that will work well.

**Comment by chrishp** [comment]
> you are using port 80 which is traditionally HTTP, with a HTTPS address. I doubt that will work well.

thank you

**Comment by chrishp** [comment]
resolved
