### ISSUE TITLE
I'm getting different errors on Chia-Blockchain on pool server

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#197]
I'm getting different errors on Chia-Blockchain on pool server:
```
2021-07-21T21:02:06.671 timelord chia.timelord.timelord   : WARNING  Too late to infuse block
2021-07-21T21:09:01.943 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chiarex/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/chiarex/chia-blockchain/chia/rpc/Ş
    raise ValueError(f"Block {header_hash.hex()} not found")
ValueError: Block 550ad2ca366a2e07add40c0d614c2c8d196b816502d55efeda79e18bf8cd07ed not found

2021-07-21T21:10:59.683 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-07-21T21:11:38.408 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chiarex/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/chiarex/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 351, in get_block_record
    raise ValueError(f"Block {header_hash.hex()} does not exist")
ValueError: Block 9a1bdb157fa8ae00313047ee2c504c29ad400eaf05dedbd4af2fb0ebeb2569fb does not exist

2021-07-21T21:11:38.436 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chiarex/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/chiarex/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 546, in get_additions_and_removals
    raise ValueError(f"Block {header_hash.hex()} not found")
ValueError: Block 9a1bdb157fa8ae00313047ee2c504c29ad400eaf05dedbd4af2fb0ebeb2569fb not found

2021-07-21T21:12:19.237 timelord chia.timelord.timelord   : WARNING  Too late to infuse block

```
Is it problem for win XCH block in our pool?

**Comment by ppolewicz** [comment]
It appears that you are running a timelord. I don't think you should be doing that.
