### ISSUE TITLE
pool not start : `CoinSolution` is now `CoinSpend`

### ISSUE THREAD

**Issue by setar** [Chia-Network/pool-reference#202]
pool-reference@main 224d0c577f8634c5b3bc24847ba3b909e3a6ff49
chia-blockchain@main 2dd4442cdde9f406862a774a87b9486969621c67

```
/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/chia/types/coin_solution.py:6: UserWarning: `CoinSolution` is now `CoinSpend`
  warnings.warn("`CoinSolution` is now `CoinSpend`")
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chia/pool-reference/pool/__main__.py", line 1, in <module>
    from pool.pool_server import main
  File "/home/chia/pool-reference/pool/pool_server.py", line 32, in <module>
    from .pool import Pool
  File "/home/chia/pool-reference/pool/pool.py", line 42, in <module>
    from chia.pools.pool_puzzles import (
ImportError: cannot import name 'get_most_recent_singleton_coin_from_coin_solution' from 'chia.pools.pool_puzzles' (/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/chia/pools/pool_puzzles.py)
```

**Comment by mariano54** [comment]
This is fixed by this:
https://github.com/Chia-Network/pool-reference/pull/168

**Comment by setar** [comment]
thanks, it work.
