### ISSUE TITLE
docker start pool-reference   SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by liutianv1** [Chia-Network/pool-reference#205]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/vpool/chiapool/pool/__main__.py", line 3, in <module>
    main()
  File "/vpool/chiapool/pool/pool_server.py", line 303, in main
    asyncio.run(start_pool_server())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/vpool/chiapool/pool/pool_server.py", line 272, in start_pool_server
    await server.start()
  File "/vpool/chiapool/pool/pool_server.py", line 58, in start
    await self.pool.start()
  File "/vpool/chiapool/pool/pool.py", line 199, in start
    self.blockchain_state = await self.node_rpc_client.get_blockchain_state()
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/chia/rpc/full_node_rpc_client.py", line 27, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/chia/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/vpool/chiapool/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host 192.168.1.42:8555 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1123)')]

**Comment by liutianv1** [comment]
I runing full_node in 192.168.1.42

**Comment by ppolewicz** [comment]
SSL doesn't really work well with IP addresses, you need to have a domain for it to work

**Comment by liutianv1** [comment]
OK，Im do it

**Comment by alierdemsunar** [comment]
check your ca bundle brother

**Comment by liutianv1** [comment]
no config and code issue . check your full_node_config @alierdemsunar
