### ISSUE TITLE
No module named 'chia.types.coin_spend'

### ISSUE THREAD

**Issue by sofregaz** [Chia-Network/pool-reference#220]
The chia version is 1.2.2, during installing the pool, throw the following error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/pool-reference/pool/__main__.py", line 1, in <module>
    from pool.pool_server import main
  File "/root/pool-reference/pool/pool_server.py", line 34, in <module>
    from .record import FarmerRecord
  File "/root/pool-reference/pool/record.py", line 6, in <module>
    from chia.types.coin_spend import CoinSpend
ModuleNotFoundError: No module named 'chia.types.coin_spend'`
please help to solve it, thanks; the OS is centos

**Comment by Playwo** [comment]
Use chia version 1.2.3
