### ISSUE TITLE
Unexpected error in create_payments_loop

### ISSUE THREAD

**Issue by DeeDab** [Chia-Network/pool-reference#243]
Got error in create_payments_loop

``` 
2021-08-29T16:34:24.016 pool root   ERROR    Unexpected error in create_payments_loop:  Traceback (most recent call last):
  File "/chia-pool/pool/pool.py", line 370, in create_payment_loop
    coin_records: List[CoinRecord] = await self.node_rpc_client.get_coin_records_by_puzzle_hash(
  File "/chia-pool/venv/lib/python3.8/site-packages/chia/rpc/full_node_rpc_client.py", line 99, in get_coin_records_by_puzzle_hash
    for coin in (await self.fetch("get_coin_records_by_puzzle_hash", d))["coin_records"]
  File "/chia-pool/venv/lib/python3.8/site-packages/chia/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError```


Chia version: 1.2.4.dev4

Why this could happened?

**Comment by jack60612** [comment]
This is a duplicate issue of #244 please close it @DeeDab
