### ISSUE TITLE
Unexpected error in get_peak_loop

### ISSUE THREAD

**Issue by DeeDab** [Chia-Network/pool-reference#244]
```

2021-08-29T14:33:06.013 pool root                         : ERROR    Unexpected error in get_peak_loop:
2021-08-29T14:33:06.014 pool root                         : ERROR    Unexpected error in collect_pool_rewards_loop:  Traceback (most recent call last):
  File "/chia-pool/pool/pool.py", line 260, in collect_pool_rewards_loop
    coin_records: List[CoinRecord] = await self.node_rpc_client.get_coin_records_by_puzzle_hashes(
  File "/chia-pool/venv/lib/python3.8/site-packages/chia/rpc/full_node_rpc_client.py", line 117, in get_coin_records_by_puzzle_hashes
    for coin in (await self.fetch("get_coin_records_by_puzzle_hashes", d))["coin_records"]
  File "/chia-pool/venv/lib/python3.8/site-packages/chia/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/chia-pool/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Chia version: 1.2.4.dev4

Why this could happened?

**Comment by jack60612** [comment]
@DeeDab your unable to connect to the node.
the error is non programmatic  please close the issue
