### ISSUE TITLE
ImportError: cannot import name AugSchemeMPL

### ISSUE THREAD

**Issue by blockinator** [Chia-Network/pool-reference#256]
I am getting this error when starting the pool:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pool-reference/pool/__main__.py", line 1, in <module>
    from pool.pool_server import main
  File "/pool-reference/pool/pool_server.py", line 11, in <module>
    from blspy import AugSchemeMPL, G2Element
ImportError: cannot import name 'AugSchemeMPL'
```

I installed the pool like so:  (NOTE: blspy~=1.0.2 in requirements.txt doesn't exist, so I used blspy~=0.1.2)
```
git clone https://github.com/Chia-Network/pool-reference

cd pool-reference && cp config-example.yaml config.yaml
```
I made the required changes to the `config.yaml` file and continued:

```
python3 -m venv ./venv

source ./venv/bin/activate

pip3 install -r requirements.txt
```

Then I started the pool like so:
```
sudo CHIA_ROOT=“/root/.chia/mainnet” ./venv/bin/python3 -m pool
```

**Comment by mariano54** [comment]
pip install -e ../chia-blockchain
OR pip install chia-blockchain

**Comment by VitalkaOdmin** [comment]
Hello. I have the following error, version blspy==2.0.2

**(venv) root@HM-a3iGE3:~/pool-reference#** sudo CHIA_ROOT="/root/.chia/testnet9" ./venv/bin/python -m pool
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/pool-reference/pool/__main__.py", line 1, in <module>
    from pool.pool_server import main
  File "/root/pool-reference/pool/pool_server.py", line 34, in <module>
    from .record import FarmerRecord
  File "/root/pool-reference/pool/record.py", line 13, in <module>
    class FarmerRecord(Streamable):
  File "/root/pool-reference/venv/lib/python3.10/site-packages/chia/util/streamable.py", line 538, in streamable
    cls._streamable_fields = create_fields(cls)
  File "/root/pool-reference/venv/lib/python3.10/site-packages/chia/util/streamable.py", line 122, in create_fields
    parse_function=function_to_parse_one_item(hint),
  File "/root/pool-reference/venv/lib/python3.10/site-packages/chia/util/streamable.py", line 431, in function_to_parse_one_item
    raise UnsupportedType(f"Type {f_type} does not have parse")
chia.util.streamable.UnsupportedType: Type <class 'blspy.G1Element'> does not have parse
**(venv) root@HM-a3iGE3:~/pool-reference#**

Can you please tell me the solution?
