### ISSUE TITLE
WARNING:pool.pool_server:Error while handling message

### ISSUE THREAD

**Issue by mssc89** [Chia-Network/pool-reference#268]
Pool is throwing this error for some of the farmers: (I replaced launcher id with ``<launcher id>``)

```
INFO:root:put_farmer response {'authentication_public_key': False, 'payout_instructions': <coroutine object Pool.validate_payout_instructions at 0x7f986d813340>}, launcher_id: <launcher id>

WARNING:pool.pool_server:Error while handling message: Traceback (most recent call last):
  File "/home/pyryk/mainnet/pool-reference/pool/pool_server.py", line 85, in inner
    res_object = await f(request)
  File "/home/pyryk/mainnet/pool-reference/pool/pool_server.py", line 209, in put_farmer
    return obj_to_response(put_farmer_response)
  File "/home/pyryk/mainnet/pool-reference/venv/lib/python3.8/site-packages/chia/util/json_util.py", line 39, in obj_to_response
    json_str = dict_to_json_str(o)
  File "/home/pyryk/mainnet/pool-reference/venv/lib/python3.8/site-packages/chia/util/json_util.py", line 31, in dict_to_json_str
    json_str = json.dumps(o, cls=EnhancedJSONEncoder, sort_keys=True)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pyryk/mainnet/pool-reference/venv/lib/python3.8/site-packages/chia/util/json_util.py", line 24, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
```

Newest Chia, newest pool-reference. What might be causing this?

**Comment by mssc89** [comment]
Only seems to happen on newer versions, it's gone on #258
