### ISSUE TITLE
chia plotnft create时显示错误  请求帮助

### ISSUE THREAD

**Issue by amumu233666** [Chia-Network/pool-reference#292]
Exception from 'wallet' Error connecting to pool https://www.chaigoukj.top:233: Cannot connect to host www.chaigoukj.top:233 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/chia/cmds/plotnft_funcs.py", line 43, in create_pool_args
    async with session.get(f"{pool_url}/pool_info", ssl=ssl_context_for_root(get_mozilla_ca_crt())) as response:
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.chaigoukj.top:233 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/chia/cmds/cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "/usr/local/lib/python3.10/dist-packages/chia/cmds/cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/usr/local/lib/python3.10/dist-packages/chia/cmds/plotnft_funcs.py", line 82, in create
    json_dict = await create_pool_args(pool_url)
  File "/usr/local/lib/python3.10/dist-packages/chia/cmds/plotnft_funcs.py", line 49, in create_pool_args
    raise ValueError(f"Error connecting to pool {pool_url}: {e}")
ValueError: Error connecting to pool https://www.chaigoukj.top:233: Cannot connect to host www.chaigoukj.top:233 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]

**Comment by amumu233666** [comment]
我使用  CHIA_ROOT=“/root/.chia/mainnet/” ./venv/bin/python -m pool   已经成功启动池CHIA_ROOT="/root/.chia/mainnet" ./venv/bin/python -m pool
INFO:root:Logging in: {'fingerprint': 4212355910, 'success': True}
INFO:root:Obtaining balance: {'confirmed_wallet_balance': 1000000000000, 'fingerprint': 4212355910, 'max_send_amount': 1000000000000, 'pending_change': 0, 'pending_coin_removal_count': 0, 'spendable_balance': 1000000000000, 'unconfirmed_wallet_balance': 1000000000000, 'unspent_coin_count': 1, 'wallet_id': 1, 'wallet_type': 0} 
使用chia plotnft create时出现错误
