### ISSUE TITLE
errors after today's update

### ISSUE THREAD

**Issue by setar** [Chia-Network/pool-reference#41]
cureent version pool-reference 830b0d0f4a5a708dea670255f82f0c350feb3a59 not work for me (the previous update I did the day before yesterday)

on branch Chia-Network/chia-blockchain.git@pools.2021-may-25
```
(venv) chia@pool:~/pool-reference$ python3 pool/pool_server.py
Traceback (most recent call last):
  File "pool/pool_server.py", line 21, in <module>
    from pool import Pool
  File "/home/chia/pool-reference/pool/pool.py", line 30, in <module>
    from singleton import create_absorb_transaction
  File "/home/chia/pool-reference/pool/singleton.py", line 20, in <module>
    POOL_ESCAPING_MOD = load_clvm("pool_escaping_innerpuz.clvm")
  File "/home/chia/chia-blockchain/chia/wallet/puzzles/load_clvm.py", line 37, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=__name__)))
  File "/home/chia/chia-blockchain/chia/wallet/puzzles/load_clvm.py", line 31, in load_serialized_clvm
    clvm_hex = pkg_resources.resource_string(package_or_requirement, hex_filename).decode("utf8")
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1142, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1388, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chia/chia-blockchain/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
```
ok, `pool_escaping_innerpuz.clvm.hex` found in branch ak.pools 
but ...
on branch Chia-Network/chia-blockchain.git@ak.pools 
```
(venv) chia@pool:~/pool-reference$ python pool/pool_server.py
Traceback (most recent call last):
  File "pool/pool_server.py", line 10, in <module>
    from chia.protocols.pool_protocol import SubmitPartial, PoolInfo
ImportError: cannot import name 'SubmitPartial' from 'chia.protocols.pool_protocol' (/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/chia/protocols/pool_protocol.py)
```

**Comment by mariano54** [comment]
Please revert if it's not working

**Comment by setar** [comment]
commit bb5ece8262c658d00c9f4e969cdbd519b40502d1 of 
chia-blockchain (5 june 2021)
file renaming

**Comment by setar** [comment]
Ок, pool now started after fix filenames https://github.com/Chia-Network/pool-reference/pull/48

But now the bundle pool (5385316ab20eac68a5f41e8ecbe8d74304d619b0) - wallet ( https://github.com/Chia-Network/chia-blockchain/commit/df0df1c3b515310346da651b3afa639514657c14 branch @pools.2021-may-25) does not work, returns error # 9
```
INFO:root:Returning {'error_code': 9, 'error_message': 'The puzzl h b489b25e6cca2c5bd9fc983a933781179bc9f718b2a1a8c6830aea91a9e36bdef8cc17a338cc8c765de3894a83945ed812307d604ac507e3ec4d61a292abbc19
0cf700b1908c45db05f73d10f07ca711f5d0dbf3a02ef0636b3e95cac6f9faf7'}, time: 0.02222299575805664 singleton: 0xe09f395c5b24d1ff5fada6cdadedf325f5a74080c1c92d9620b269caccbf0414
```
The same plots worked correctly earlier
