### ISSUE TITLE
Run pool_server.py error.

### ISSUE THREAD

**Issue by chenhonghe** [Chia-Network/pool-reference#53]
CHIA_ROOT="/data/chia-blockchain/.chia/testnet7" ./venv/bin/python pool/pool_server.py

Error info
```
Traceback (most recent call last):
  File "pool/pool_server.py", line 21, in <module>
    from pool import Pool
  File "/data/pool-reference/pool/pool.py", line 30, in <module>
    from singleton import create_absorb_transaction
  File "/data/pool-reference/pool/singleton.py", line 20, in <module>
    POOL_ESCAPING_MOD = load_clvm("pool_escaping_innerpuz.clvm")
  File "/data/pool-reference/venv/lib/python3.7/site-packages/chia/wallet/puzzles/load_clvm.py", line 37, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=__name__)))
  File "/data/pool-reference/venv/lib/python3.7/site-packages/chia/wallet/puzzles/load_clvm.py", line 31, in load_serialized_clvm
    clvm_hex = pkg_resources.resource_string(package_or_requirement, hex_filename).decode("utf8")
  File "/data/pool-reference/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1210, in resource_string
    self, resource_name
  File "/data/pool-reference/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1452, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/data/pool-reference/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1572, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/data/pool-reference/venv/lib/python3.7/site-packages/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
```

**Comment by chenhonghe** [comment]
https://github.com/Chia-Network/pool-reference/issues/45
