### ISSUE TITLE
Error claiming rewards

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/pool-reference#57]
Unexpected error in collect_pool_rewards_loop:  Traceback (most recent call last):
  File "data/chia/pool-reference/pool/pool.py", line 279, in collect_pool_rewards_loop
    spend_bundle = await create_absorb_transaction(
  File "data/chia/pool-reference/pool/singleton.py", line 135, in create_absorb_transaction
    absorb_spend: List[CoinSolution] = create_absorb_spend(
  File "data/chia/pool-reference/venv/lib64/python3.8/site-packages/chia/pools/pool_puzzles.py", line 215, in create_absorb_spend
    assert full_puzzle.get_tree_hash() == coin.puzzle_hash
AssertionError

**Comment by mariano54** [comment]
I think this was just an old plot

**Comment by pajche** [comment]
> I think this was just an old plot

Recreated all plots yesterday, pulled new updates, reinstalled everything, after almost a day I got the same error.
