### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure

### ISSUE THREAD

**Issue by yhhwpp** [Chia-Network/pool-reference#98]
run `sudo CHIA_ROOT="/your/home/dir/.chia/testnet7" ./venv/bin/python pool/pool_server.py` Throws the following error

```
Traceback (most recent call last):
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pool/pool_server.py", line 287, in <module>
    asyncio.run(start_pool_server())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "pool/pool_server.py", line 258, in start_pool_server
    await server.start()
  File "pool/pool_server.py", line 57, in start
    await self.pool.start()
  File "/home/text/chia/pool-reference/pool/pool.py", line 182, in start
    self.blockchain_state = await self.node_rpc_client.get_blockchain_state()
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/chia/rpc/full_node_rpc_client.py", line 27, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/chia/rpc/rpc_client.py", line 41, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/home/text/chia/pool-reference/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host localhost:8555 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1076)')]
```

**Comment by mariano54** [comment]
Did you install chia-blockchain properly beforehand, and run the full node? Can you access the full node RPC through curl?
https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces

**Comment by yhhwpp** [comment]
chia-blockchain has installed,  8555 port also running， then I solved by res-install
